repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.64.1
  hooks:
  - id: terraform_validate
  - id: terraform_fmt
  - id: terraform_tflint
  - id: terraform_tfsec
